import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { createClient } from "@/utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabse = createClient();
  const { data: { user }, error } = await supabse.auth.getUser();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
